# Generated by Django 4.2.21 on 2025-08-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0002_alter_absent_responder_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'ordering': ['-create_time']},
        ),
    ]
